// <auto-generated />
using System;
using Cwiczenia7.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cwiczenia7.Migrations
{
    [DbContext(typeof(masterContext))]
    [Migration("20220620075640_FinalMigration")]
    partial class FinalMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Latin1_General_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cwiczenia7.Models.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("IdClient")
                        .HasName("Client_pk");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("Cwiczenia7.Models.ClientTrip", b =>
                {
                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.Property<int>("IdTrip")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime");

                    b.HasKey("IdClient", "IdTrip")
                        .HasName("Client_Trip_pk");

                    b.HasIndex("IdTrip");

                    b.ToTable("Client_Trip");
                });

            modelBuilder.Entity("Cwiczenia7.Models.Country", b =>
                {
                    b.Property<int>("IdCountry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("IdCountry")
                        .HasName("Country_pk");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("Cwiczenia7.Models.CountryTrip", b =>
                {
                    b.Property<int>("IdCountry")
                        .HasColumnType("int");

                    b.Property<int>("IdTrip")
                        .HasColumnType("int");

                    b.HasKey("IdCountry", "IdTrip")
                        .HasName("Country_Trip_pk");

                    b.HasIndex("IdTrip");

                    b.ToTable("Country_Trip");
                });

            modelBuilder.Entity("Cwiczenia7.Models.Trip", b =>
                {
                    b.Property<int>("IdTrip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<int>("MaxPeople")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("IdTrip")
                        .HasName("Trip_pk");

                    b.ToTable("Trip");
                });

            modelBuilder.Entity("Cwiczenia7.Models.ClientTrip", b =>
                {
                    b.HasOne("Cwiczenia7.Models.Client", "IdClientNavigation")
                        .WithMany("ClientTrips")
                        .HasForeignKey("IdClient")
                        .HasConstraintName("Table_5_Client")
                        .IsRequired();

                    b.HasOne("Cwiczenia7.Models.Trip", "IdTripNavigation")
                        .WithMany("ClientTrips")
                        .HasForeignKey("IdTrip")
                        .HasConstraintName("Table_5_Trip")
                        .IsRequired();

                    b.Navigation("IdClientNavigation");

                    b.Navigation("IdTripNavigation");
                });

            modelBuilder.Entity("Cwiczenia7.Models.CountryTrip", b =>
                {
                    b.HasOne("Cwiczenia7.Models.Country", "IdCountryNavigation")
                        .WithMany("CountryTrips")
                        .HasForeignKey("IdCountry")
                        .HasConstraintName("Country_Trip_Country")
                        .IsRequired();

                    b.HasOne("Cwiczenia7.Models.Trip", "IdTripNavigation")
                        .WithMany("CountryTrips")
                        .HasForeignKey("IdTrip")
                        .HasConstraintName("Country_Trip_Trip")
                        .IsRequired();

                    b.Navigation("IdCountryNavigation");

                    b.Navigation("IdTripNavigation");
                });

            modelBuilder.Entity("Cwiczenia7.Models.Client", b =>
                {
                    b.Navigation("ClientTrips");
                });

            modelBuilder.Entity("Cwiczenia7.Models.Country", b =>
                {
                    b.Navigation("CountryTrips");
                });

            modelBuilder.Entity("Cwiczenia7.Models.Trip", b =>
                {
                    b.Navigation("ClientTrips");

                    b.Navigation("CountryTrips");
                });
#pragma warning restore 612, 618
        }
    }
}
